version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_HOST: ${DB_HOST}
    ports:
      - "3307:3306"
    expose:
      - 3307
    healthcheck:
      test: ["CMD", "mariadb", "-hlocalhost", "-uroot", "-p${DB_PWD}", "-e", "SELECT 1"]
      retries: 10
      timeout: 20s
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "/wait && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=20
      - WAIT_HOST_CONNECT_TIMEOUT=20

volumes:
  mariadb_data:
